### ISSUE TITLE
CMake Error, with ROOT v6.26/06

### ISSUE THREAD

**Issue by QZ4869** [eguiraud/root_dictionaries_tutorial#3]
I first build the ROOT v6.26/06 on my ubuntu18.04
like this
```bash
git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src
cmake -DCMAKE_INSTALL_PREFIX=/data3/ROOT/root_install -Dall=ON /data3/ROOT/root_src/
cmake --build . --target install -j30
```
then, build the example `with_cmake` in this repository:
```
. /data3/ROOT/root_install/bin/thisroot.sh
git clone https://github.com/eguiraud/root_dictionaries_tutorial
mkdir root_dictionaries_tutorial/with_cmake/build
cd root_dictionaries_tutorial/with_cmake/build
cmake ../
```
then I get `CMake Error`:
```bash
-- Looking for ROOT
-- ROOT 6.26.06 found at /data3/ROOT/root_install/bin
-- Configuring done
CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


CMake Error at /data3/ROOT/root_install/cmake/RootMacros.cmake:642 (add_custom_command):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:$<TARGET_PROPERTY:readwrite_twoints,INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  CMakeLists.txt:15 (ROOT_GENERATE_DICTIONARY)


-- Generating done
-- Build files have been written to: /data3/ROOT/About_Dict_Cmake/root_dictionaries_tutorial/with_cmake/build
```

I can continue to make and run this example, but this `CMake Error` makes me very comfused. I'm not familiar with CMake, so I need some help, any comment will be helpful, thanks!

By the way, it will no `CMake Error` if I use ROOT 6.22/06.

**Comment by eguiraud** [comment]
Hi,

> it will no CMake Error if I use ROOT 6.22/06.

this suggests that ROOT v6.26/06 uses cmake features that are too new for the cmake version in Ubuntu 18.04.

You can use an older ROOT or a newer cmake/Ubuntu. I will inform the ROOT build system maintainer that we might have to increase the minimum required cmake version.

Cheers,
Enrico

**Comment by eguiraud** [comment]
By the way, what is your cmake version (`cmake --version`)?

**Comment by eguiraud** [comment]
Also note that Ubuntu 18.04 is end of life and it does not receive security updates anymore unless you have a paid ESM subscription: see https://ubuntu.com/about/release-cycle -- I would strongly suggest to update :smile:

**Comment by QZ4869** [comment]
Hi Enrico, Thank you very much!
I changed the version of cmake from `3.10.2` to `3.24.0`, it works! No more `CMake Error`.

By the way, I have another question want your help, if I want to generate the dynamic library for class twoints in this `with_cmake` example, to use it in ROOT prompt interactively, and only need one commend before use ROOT, like
`export LD_LIBRARY_PATH=/data3/ROOT/root_dictionaries_tutorial/with_cmake/build/lib:$LD_LIBRARY_PATH`.

If I want to do this, how can I change the `CMakeLists.txt` in `with_cmake` example.

Thanks again!

**Comment by eguiraud** [comment]
Hi @QZ4869 ,

For your latter question, please ask on https://root-forum.cern.ch -- that's the official support channel. 

I'd also have a question: the first line in ROOT's main `CMakeLists.txt`, for the git tag `v6-26-06`, is `cmake_minimum_required(VERSION 3.16 FATAL_ERROR)`. So I am surprised you could even start a build with cmake `3.10.2`? Did you change that line, or what git commit were you using exactly?

**Comment by QZ4869** [comment]
I have two cmake in my ubuntu, the default is `3.10.2`, I used the cmake `3.24.0` to make the root `v6-26-06` before(because the cmake_minimum_required), and use the default version for this example, sorry for making you confused.

**Comment by eguiraud** [comment]
Ok, this is understood and fixed then :+1:
